server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/pagamento?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue
security:
  jwt:
    token:
      secret-key: chave_microservices

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka/

